/*
 * generated by Xtext 2.15.0
 */
package org.contextmapper.dsl.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class ContextMappingDSLProposalProvider extends AbstractContextMappingDSLProposalProvider {
}
