/*
 * generated by Xtext 2.15.0
 */
package org.contextmapper.tactic.dsl.ide


/**
 * Use this class to register ide components.
 */
class TacticDDDLanguageIdeModule extends AbstractTacticDDDLanguageIdeModule {
}
