/*
 * generated by Xtext 2.15.0
 */
package org.contextmapper.dsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ContextMappingDSLStandaloneSetup extends ContextMappingDSLStandaloneSetupGenerated {

	def static void doSetup() {
		new ContextMappingDSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
