/*
 * generated by Xtext 2.15.0
 */
package org.contextmapper.servicecutter.dsl.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class ServiceCutterConfigurationDSLUiModule extends AbstractServiceCutterConfigurationDSLUiModule {
}
