/*
 * generated by Xtext 2.15.0
 */
package org.contextmapper.dsl.ide


/**
 * Use this class to register ide components.
 */
class ContextMappingDSLIdeModule extends AbstractContextMappingDSLIdeModule {
}
