/*
 * generated by Xtext 2.15.0
 */
package org.contextmapper.servicecutter.dsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ServiceCutterConfigurationDSLStandaloneSetup extends ServiceCutterConfigurationDSLStandaloneSetupGenerated {

	def static void doSetup() {
		new ServiceCutterConfigurationDSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
