/*
 * generated by Xtext 2.32.0
 */
package org.contextmapper.servicecutter.dsl.ide


/**
 * Use this class to register ide components.
 */
class ServiceCutterConfigurationDSLIdeModule extends AbstractServiceCutterConfigurationDSLIdeModule {
}
