/*
 * generated by Xtext 2.15.0
 */
package org.contextmapper.tactic.dsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class TacticDDDLanguageStandaloneSetup extends TacticDDDLanguageStandaloneSetupGenerated {

	def static void doSetup() {
		new TacticDDDLanguageStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
